name: Preview

# 执行 CI 的时机: 当 git push 到 feature-* 分支时
on:
  push:
    branches:    
      - 'feature-*'

# 执行所有的 jobs
jobs:
  preview:
    runs-on: self-hosted
    environment:
      # 获取 CICD 中的变量: Context
      # https://docs.github.com/en/actions/learn-github-actions/expressions
      name: preview/${{ github.ref_name }}
      url: https://cra.${{ github.ref_name	}}.shanyue.tech
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
      - run: pwd && ls -lah
      - name: Preview
        run: docker-compose -f domain.docker-compose.yaml up --build -d
        env:
          REF_NAME: ${{ github.ref_name }}